### ISSUE TITLE
fluent-bit sidecar Mount hostPath /var/log/pods

### ISSUE THREAD

**Issue by g-bohncke** [TIBCOSoftware/tp-helm-charts#105]
Currently all the fluent-bit sidecars mount the host file system.

```
- name: podlogs
  hostPath:
    path: /var/log/pods
    type: Directory
```
[example](https://github.com/TIBCOSoftware/tp-helm-charts/blob/main/charts/dp-core-infrastructure/charts/tp-tibtunnel/templates/deployment.yaml#L163)

This is a security risk since this allows access to logs of other pods on the host. Normaly the practice with a fluent-bit sidcar is to mount an empty volume which is used to ship the logs from.
This would also eliminate the issue mention in some of the config file # GitHub issue: https://github.com/fluent/fluent-bit/issues/872#issuecomment-827763207 since you don't need to access /var/log/pods

```
apiVersion: v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template: 
    metadata: 
      ...
    spec:
      volumes:
        - name: app-logs
          emptyDir: {}
      containers:
        - name: application
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          ...
        - name: fluent-bit
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
          ...
```
